### ISSUE TITLE
Migrating from CRACO to CRA

### ISSUE THREAD

**Issue by hytalo-bassi** [TifuDev/frontifu#6]
CRACO has used at the beggining of project as a way of using TailwindCSS because CRA did not support.

Now, with the new version of [TailwindCSS](https://tailwindcss.com/docs/guides/create-react-app) and CRA it's possible!

There is some advantages using CRA:
- That is the default
- Avoid some problems
- More updated

**Comment by C0meb4ck** [comment]
Acho que não deveríamos usar crack amigo

**Comment by hytalo-bassi** [comment]
Error when trying to build application with `yarn build`
```
TypeError: MiniCssExtractPlugin is not a constructor
```

That is because the lib that exports MiniCssExtractPlugin have changed it exports.
The current exports is showed right below:
```
> console.log(MiniCssExtractPlugin)
{
  default: [class MiniCssExtractPlugin] {
    loader: '/node_modules/mini-css-extract-plugin/dist/loader.js'
  },
  pluginName: 'mini-css-extract-plugin',
  pluginSymbol: Symbol(mini-css-extract-plugin)
}
```
The webpack.config.js must call the constructor `default` instead of  MiniCssExtractPlugin

**Comment by hytalo-bassi** [comment]
Migration complete in merge ed9af658b445236432cd772e4dfe23fde98990b6
